name: Deploy to Render

on:
  push:
    branches:
      - main  # Triggers deployment when code is pushed to 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render Deploy
        run: curl -X GET ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
